### PR TITLE
CMAKE: added CMP0063 policy to new

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@dmatveev please, review

**Comment by dmatveev** [comment]
What does this thing do?

**Comment by ilya-lavrenov** [comment]
https://cmake.org/cmake/help/v3.3/policy/CMP0063.html

Allows to set visibility settings globally via cmake variables. Otherwise, we have cmake warnings

**Comment by dmatveev** [comment]
Merged, thanks!

**Pull request merged**
