### PR TITLE
Replaced CI badge with self-hosted CI badge

### PR DESCRIPTION
**Pull request by asmorkalov**

### CODE REVIEW

**Comment by Hardcode84** [comment]
I think it is possible to have multiple Ci badges

**Comment by dmatveev** [comment]
I believe this is no longer relevant.. But @alexgiving can you please modify it so the Github Actions-based status would make the badge? Would it work this way?

**Comment by alexgiving** [comment]
@dmatveev I suggest to add Actions badge in PR https://github.com/opencv/ade/pull/30

**Comment by dmatveev** [comment]
Yeah let's close this one

**Pull request closed without merging**
